Email notifications next
ReliefApplications/ems-backend pull request #1005
Opened 2024-03-25 14:44 UTC by AntoineRelief

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- Please insert link to ticket
- Please insert link to front-end branch if any
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-backend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

2024-04-17 03:54 UTC, HasnatL-Adapptlimited commented
Hi @AntoineRelief , @MwanPygmay, @matheus-relief 
cc: @morgang-adappt 

The following changes have been implemented:

- Legacy Styling Implemented (Emails display consistently across a majority of browsers)
- Data Persisting fix in frontend, also made to the final email

2024-04-23 16:15 UTC, Matthis-M-ReliefApps requested changes
Hi @HasnatL-Adapptlimited,
Review done there too. The only thing that seems possibly critical to me is the permissions issue.
The naming changes on DB structure should also be done as early as possible to avoid the need of migrations.
Please let me know if any of my comments is unclear.
All the rest looks mostly good, thank you for your work!

2024-04-23 16:15 UTC, Matthis-M-ReliefApps commented on src/schema/types/dataSet.type.ts
### HIGH PRIORITY
I don't think the "S" in "dataSet" should be capitalized
(putting as high priority because waiting before implementing this change could make it more troublesome to solve)

2024-04-23 16:15 UTC, Matthis-M-ReliefApps commented on src/schema/types/dataSet.type.ts
> +          // console.log(parent.records);
remove

2024-04-23 16:15 UTC, Matthis-M-ReliefApps commented on src/schema/types/emailNotification.type.ts
> +});
Naming to fix as described in previous comment

2024-04-23 16:15 UTC, Matthis-M-ReliefApps commented on src/utils/schema/resolvers/Query/getFilter.ts
@AntoineRelief Is think this part of the code is/will be changed by a fix that Matthieu developed for the "today" function, you might have some merge conflict

2024-04-23 16:15 UTC, Matthis-M-ReliefApps commented on src/utils/notification/htmlBuilder.ts
> +      });
Could we make those localeFormats constants so they can be changed easily if required?

2024-04-23 16:15 UTC, Matthis-M-ReliefApps commented on src/utils/notification/htmlBuilder.ts
> +        newHeader = `From ${formattedPastDate} ${formattedPastTime} UTC as of ${formattedCurrentDate} ${formattedCurrentTime} UTC`;
I didn't check by running the code, so I'm not too sure where they are displayed/used, but they probably should be translated when needed.

2024-06-21 13:16 UTC, merged