Ab#80203 remove graphql from export functions
ReliefApplications/ems-backend pull request #847
Opened 2023-12-01 13:00 UTC by MwanPygmay

# Description

Remove graphql from the export to improve performance. Resources, resource, and calculated fields (even nested) are supported.

## Useful links

- [Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/80203/)
- Please insert link to front-end branch if any

## Type of change

- [ ] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

Created resource with 11000 records, with a calculated field. Tested performance for this resource.
Tested csv, xlsx, resource and resources fields.

## Screenshots

Performance with and without graphql for 10 takes:
<img width="902" alt="Screenshot 2023-12-01 at 13 18 33" src="https://github.com/ReliefApplications/ems-backend/assets/59645813/07b371dc-f403-4b8b-ad8a-f2cea97b2073">

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-backend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-12-05 11:17 UTC, unai-reliefapp requested changes

2023-12-05 11:17 UTC, unai-reliefapp commented on src/utils/files/exportBatch.ts
> +  console.log(records.slice(0, 5));
![image](https://github.com/ReliefApplications/ems-backend/assets/123092672/5c1cbc1b-28fc-4bb9-a9b5-c685b56dabf0)
```suggestion
```

2023-12-05 11:17 UTC, unai-reliefapp commented on src/utils/files/exportBatch.ts
> +  console.log(records.slice(0, 5));
![image](https://github.com/ReliefApplications/ems-backend/assets/123092672/1dde89a5-2685-4d38-8d71-ab8b23fed283)

```suggestion
```

2023-12-05 17:20 UTC, estelafs approved these changes
Everything is working as expected

2024-01-02 16:34 UTC, AntoineRelief commented
made some improvements to it:
- better performance, indeed, a for loop on items fetched for related resources would take too much time ( doing one query per record is more efficient it seems )
- use datastream
- use existing function to write values from columns meta

to be done:
- check if working when using reference data questions, I had to comment this part to make some improvements
- not working for some resource(s) links. If the resource(s) question is part of the resource you export, it is working fine, but it you are using a query where the link is coming from the other resource ( question using currently exported resource ), it won't work. We should check how we did that when using graphql ( in the src / utils / schema / resolvers / entity file ) as it is working fine there

2024-01-10 09:19 UTC, MwanPygmay commented
- Fix some bugs, notably for resource/resources/reference data questions
- Changed a bit @LenaelleRelief's logic to get the parent resource(s) directly from the front (see front PR) => this also fetches the children resources (not resource), but did not find how to avoid it, and it causes no bug, just some optimization. This avoids some problems, Lenaelle searched for parent resource(s) by field and it could lead to some problem if several resources had the same field. The new method should be sure.

2024-01-29 18:35 UTC, closed without merging

2024-01-29 18:35 UTC, AntoineRelief commented
now using this pr:
https://github.com/ReliefApplications/ems-backend/pull/961